apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: skjermen
spec:
  environments:
    - name: test
      build:
        from: master
    - name: production
      build:
        from: production
  components:
    - name: main
      src: "./webapp"
      public: true
      ports:
        - name: http
          port: 80
  dnsAppAlias:
    environment: production
    component: main
